[package]
name = "lock_rotations"
version = "0.1.0"
authors = ["David Gay <david.gay@gtri.gatech.edu>", "Erich Lohrmann <erich.lohrmann@gtri.gatech.edu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
